export enum Status {
    NON_TRAITEE = 'NON_TRAITEE',
    EN_COURS = 'EN_COURS',
    TRAITEE = 'TRAITEE',
    DISPONIBLE = 'DISPONIBLE',
    INDISPONIBLE = 'INDISPONIBLE'
}

export enum Statut {
    NON_TRAITEE = 'NON_TRAITEE',
    EN_COURS = 'EN_COURS',
    TRAITEE = 'TRAITEE',
    DISPONIBLE = 'DISPONIBLE',
    INDISPONIBLE = 'INDISPONIBLE'
}
