# Port d'écoute standard MQTT
listener 1883 0.0.0.0

# Fichier de persistance des données
persistence true
persistence_location /mosquitto/data/

# Fichiers de logs
log_dest file /mosquitto/log/mosquitto.log
log_dest stdout

# Sécurité : on interdit les connexions anonymes
allow_anonymous false

# Chemin vers le fichier contenant les mots de passe
password_file /mosquitto/config/pwfile