"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La valeur en dur ne sert que de repli pour le dev local sans env configuré ; en
# production, SECRET_KEY doit toujours être fourni via l'environnement.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-HSLgGBNlaGBJ4kyaracScLRPa3tFJhK6LOEbYQs9ipBu-DaMMQfey725-fB-uq8Dabk',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost', '172.16.1.113', '172.16.1.114', '127.0.0.1',
    'assista-crise.fr', 'www.assista-crise.fr', 'demo.assista-crise.fr', 'assista-crise.duckdns.org',
    # Nom réseau Docker interne : nécessaire pour qu'un service du même réseau (ex: le
    # service-pont meshcore-bridge/) puisse appeler l'API via http://backend:8000/ plutôt
    # que par l'IP publique — sans ça Django répond 400 (DisallowedHost) à toute requête
    # portant ce Host, même en interne.
    'backend',
]

CSRF_TRUSTED_ORIGINS = [
    "https://assista-crise.fr",
    "https://www.assista-crise.fr",
    "https://demo.assista-crise.fr",
    "https://demo.assista-crise.fr:4200",
    "https://assista-crise.duckdns.org",

    "http://172.16.1.113",
    "https://172.16.1.113",
    "http://172.16.1.113:4200",

    "http://localhost",
    "http://localhost:4200",
]

# Custom user model
AUTH_USER_MODEL = 'core.User'


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'django_filters',
    'core',
    "django.contrib.gis",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.NoCacheApiMiddleware',
    'core.middleware.AuditTraceMiddleware',
    'core.middleware.GeoResolutionBudgetMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.environ.get('DB_NAME', 'assista-db'),
        # Pas de valeur par défaut pour USER/PASSWORD (contrairement à avant, où le repli
        # 'admin'/'admin' codé en dur ici correspondait EXACTEMENT aux identifiants réellement
        # utilisés en prod, jamais changés) : mieux vaut un démarrage qui échoue bruyamment
        # (KeyError) qu'un repli silencieux vers un identifiant faible.
        'USER': os.environ['DB_USER'],
        'PASSWORD': os.environ['DB_PASS'],
        'HOST': os.environ.get('DB_HOST', 'db'),
        'PORT': '5432',
        # Le rôle applicatif (assista_app) n'est pas superuser et ne peut donc pas exécuter
        # CREATE EXTENSION lui-même sur une base de test fraîche : on clone plutôt
        # template_postgis (PostGIS déjà installé), dont assista_app est propriétaire — voir
        # le commit qui a remplacé l'ancien rôle "admin" (superuser) par ce rôle à droits
        # limités.
        'TEST': {
            'NAME': 'test_assista-db',
            'TEMPLATE': 'template_postgis',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# MEDIA files (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

CORS_ALLOWED_ORIGINS = [
    "http://172.16.1.113:4200",
    "http://assista-crise.duckdns.org",
    "http://demo.assista-crise.fr",
    "http://localhost:4200",
    "http://127.0.0.1:4200",
    "http://frontend:4200",  # Pour Docker
    "https://172.16.1.113:4200",
    "https://assista-crise.duckdns.org",
    "https://assista-crise.fr",
    "https://demo.assista-crise.fr",
    "https://demo.assista-crise.fr:4200",
    "https://localhost:4200",
    "https://127.0.0.1:4200",
    "https://frontend:4200",  # Pour Docker
]

CORS_ALLOW_CREDENTIALS = True

# Permettre tous les headers et méthodes pour le développement
CORS_ALLOW_ALL_ORIGINS = False  # Garder False pour la sécurité
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
        # 'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
    ],
}

# JWT Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

AUTH_USER_MODEL = 'core.User'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.environ.get('EMAIL_HOST', 'mailhog')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 1025))

EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False') == 'True'
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'

EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@assista-crise.fr')

SERVER_URL = os.environ.get(
    "SERVER_URL",
    "https://www.assista-crise.fr"
)

# Durée de conservation (en jours) des lignes de la main courante (AuditLog),
# purgées par `python manage.py purge_audit_logs` (principe de minimisation RGPD).
AUDIT_LOG_RETENTION_DAYS = int(os.environ.get('AUDIT_LOG_RETENTION_DAYS', 30))

# Seuils de dérivation de l'état Actif/Inactif/Perdu d'un Satellite (voir Satellite.etat,
# core/serializers.py) à partir de `dernier_contact` — chaque appel authentifié réussi d'un
# satellite (pas de heartbeat séparé) met à jour ce champ. Volontairement configurables plutôt
# qu'en dur : le bon réglage dépendra du retour terrain, comme cela a été le cas pour
# SILENCE_FIN_REPONSE côté proxy MeshCore.
SATELLITE_SEUIL_INACTIF_MINUTES = int(os.environ.get('SATELLITE_SEUIL_INACTIF_MINUTES', 15))
SATELLITE_SEUIL_PERDU_MINUTES = int(os.environ.get('SATELLITE_SEUIL_PERDU_MINUTES', 120))

# Rayon (km) utilisé par SatelliteViewSet.supervision pour approximer les communes
# "limitrophes" d'une institution communale — le référentiel Commune ne conserve que des
# centroïdes (voir Commune.__doc__), pas de géométrie précise, donc pas de vraie adjacence de
# polygones possible ici : distance de centroïde à centroïde, candidates restreintes au même
# département. Approximation assumée, à affiner si des géométries communales précises entrent
# un jour en base.
SATELLITE_SUPERVISION_RAYON_LIMITROPHE_KM = int(os.environ.get('SATELLITE_SUPERVISION_RAYON_LIMITROPHE_KM', 15))

# Active la file de synchronisation local -> central (core/sync_outbox.py) : seule une
# instance Full de satellite (backend local tournant sur le Pi) doit peupler la file à chaque
# écriture locale — le central ne doit jamais le faire (sinon boucle : le central "synchronise
# vers lui-même"). Réglé explicitement à True uniquement dans satellite/.env.example (profil
# full), absent/False partout ailleurs.
INSTANCE_SATELLITE_LOCALE = os.environ.get('INSTANCE_SATELLITE_LOCALE', 'False') == 'True'

# Intervalle (secondes) entre deux tentatives de la commande synchroniser_sortant côté
# satellite Full — voir satellite/docker-compose.yml, service sync-sortant. Toujours tentée,
# que le central soit vu en ligne ou non par etat_connectivite.py (décision utilisateur du
# 2026-09-18) : ce paramètre n'a de sens que côté satellite, mais vit ici pour rester cohérent
# avec les autres seuils SATELLITE_* déjà en settings plutôt que dans un fichier à part.
SATELLITE_SYNC_SORTANT_INTERVALLE_S = int(os.environ.get('SATELLITE_SYNC_SORTANT_INTERVALLE_S', 300))

# Identifiants du compte de service de CE satellite auprès du central, utilisés par la
# commande de gestion `synchroniser_sortant` (voir satellite/docker-compose.yml, service
# sync-sortant) — mêmes valeurs que le pont MeshCore/Meshtastic utilise déjà pour s'authentifier
# (DJANGO_EMAIL/DJANGO_PASSWORD côté bridge), mais nommées ici SATELLITE_* pour ne pas laisser
# penser qu'elles configurent CE backend lui-même (elles configurent ce qu'il appelle).
# SATELLITE_ID : uuid renvoyé par l'API à l'enrôlement (voir installer.sh, phase "enroler").
SATELLITE_CENTRAL_URL = os.environ.get('SATELLITE_CENTRAL_URL', '')
SATELLITE_ID = os.environ.get('SATELLITE_ID', '')
SATELLITE_EMAIL = os.environ.get('SATELLITE_EMAIL', '')
SATELLITE_PASSWORD = os.environ.get('SATELLITE_PASSWORD', '')

# Identité du sous-traitant pour le corps de l'email envoyé à l'acceptation de la convention de
# sous-traitance RGPD (voir core/convention_sous_traitance.py) — mêmes coordonnées que /rgpd et
# /mentions-legales côté frontend (protégées d'une lecture directe côté client, mais un email
# adressé nommément à son destinataire n'a pas cette contrainte : le contenu doit être lisible).
CONVENTION_SOUS_TRAITANT_NOM = os.environ.get('CONVENTION_SOUS_TRAITANT_NOM', 'Sylvain HAZERA')
CONVENTION_SOUS_TRAITANT_ADRESSE = os.environ.get(
    'CONVENTION_SOUS_TRAITANT_ADRESSE', '5 place Gabriel Fauré, 33200 Bordeaux',
)
CONVENTION_SOUS_TRAITANT_EMAIL = os.environ.get('CONVENTION_SOUS_TRAITANT_EMAIL', 'contact@assista-crise.fr')

USE_X_FORWARDED_HOST = True

SECURE_PROXY_SSL_HEADER = (
    ('HTTP_X_FORWARDED_PROTO', 'https')
)

# Activés seulement hors DEBUG pour ne pas casser le dev local en HTTP.
if not DEBUG:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

