server {
    listen 80;

    # Tout ce qui commence par /api va vers le Backend Python
    location /api {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # L'interface d'admin Django
    location /admin {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
    }

    # Le reste va vers le Frontend Angular
    location / {
        proxy_pass http://frontend:4200;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}