# Generated by Django 5.2.11 on 2026-03-03 13:13

import core.validators
import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/', validators=[core.validators.validate_image_file])),
                ('type', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AUT_LOCALE', 'Autorité locale'), ('SECOURS', 'Secours organisés'), ('UTIL_SIMPLE', 'Utilisateur')], default='UTIL_SIMPLE', max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=5, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crisis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/crises/')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_crises', to=settings.AUTH_USER_MODEL)),
                ('validator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_crises', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='affected_crisis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victims', to='core.crisis'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/informations/', validators=[core.validators.validate_image_file])),
                ('first_name_information', models.CharField(max_length=60)),
                ('last_name_information', models.CharField(max_length=80)),
                ('email_information', models.EmailField(max_length=254)),
                ('phone_information', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_informations', to=settings.AUTH_USER_MODEL)),
                ('crisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informations', to='core.crisis')),
                ('information_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='core.informationtype')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_informations',
            field=models.ManyToManyField(blank=True, related_name='viewing_users', to='core.information'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/offres/', validators=[core.validators.validate_image_file])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('first_name_offer', models.CharField(max_length=60)),
                ('last_name_offer', models.CharField(max_length=80)),
                ('email_offer', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_offers', to=settings.AUTH_USER_MODEL)),
                ('crisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='core.crisis')),
                ('offer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.offertype')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_offers',
            field=models.ManyToManyField(blank=True, related_name='viewing_users', to='core.offer'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/demandes/', validators=[core.validators.validate_image_file])),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('first_name_request', models.CharField(max_length=60)),
                ('last_name_request', models.CharField(max_length=80)),
                ('email_request', models.EmailField(max_length=254)),
                ('phone_request', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='NON_TRAITEE', max_length=20)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_requests', to=settings.AUTH_USER_MODEL)),
                ('crisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.crisis')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='core.requesttype')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='viewed_requests',
            field=models.ManyToManyField(blank=True, related_name='viewing_users', to='core.request'),
        ),
    ]
