# Generated by Django 5.2.10 on 2026-01-20 12:40

import django.contrib.auth.models
import django.contrib.auth.validators
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeInformation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOffre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone_utilisateur', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('type', models.CharField(choices=[('ADMIN', 'Administrateur'), ('AUT_LOCALE', 'Autorité locale'), ('SECOURS', 'Secours organisés'), ('UTIL_SIMPLE', 'Utilisateur')], default='UTIL_SIMPLE', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Crise',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crises_validees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='crise_touchee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='victimes', to='core.crise'),
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/demandes/')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('prenom_demande', models.CharField(max_length=60)),
                ('nom_demande', models.CharField(max_length=80)),
                ('email_demande', models.EmailField(max_length=254)),
                ('telephone_demande', models.CharField(max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='NON_TRAITEE', max_length=20)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_saisies', to=settings.AUTH_USER_MODEL)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='core.crise')),
                ('type_demande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to='core.typedemande')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='consulte_demande',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_consultant', to='core.demande'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/informations/')),
                ('prenom_information', models.CharField(max_length=60)),
                ('nom_information', models.CharField(max_length=80)),
                ('email_information', models.EmailField(max_length=254)),
                ('telephone_information', models.CharField(max_length=20)),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informations_saisies', to=settings.AUTH_USER_MODEL)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informations', to='core.crise')),
                ('type_information', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='core.typeinformation')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='consulte_information',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_consultant', to='core.information'),
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/materiel/')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('est_emprunte', models.BooleanField(default=False)),
                ('date_emprunt', models.DateTimeField(blank=True, null=True)),
                ('date_rendu', models.DateTimeField(blank=True, null=True)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='core.crise')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='consulte_materiel',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_consultant', to='core.materiel'),
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/offres/')),
                ('localisation', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('prenom_offre', models.CharField(max_length=60)),
                ('nom_offre', models.CharField(max_length=80)),
                ('email_offre', models.EmailField(max_length=254)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('NON_TRAITEE', 'Non traitée'), ('EN_COURS', 'En cours de traitement'), ('TRAITEE', 'Traitée'), ('DISPONIBLE', 'Disponible'), ('INDISPONIBLE', 'Indisponible')], default='DISPONIBLE', max_length=20)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_saisies', to=settings.AUTH_USER_MODEL)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='core.crise')),
                ('materiel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offre', to='core.materiel')),
                ('type_offre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offres', to='core.typeoffre')),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='consulte_offre',
            field=models.ManyToManyField(blank=True, related_name='utilisateurs_consultant', to='core.offre'),
        ),
    ]
