# Generated by Django 5.2.10 on 2026-01-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offre',
            name='materiel',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='consulte_materiel',
        ),
        migrations.DeleteModel(
            name='Materiel',
        ),
    ]
