# Generated by Django 5.2.11 on 2026-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='radius',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='crisis',
            name='type',
            field=models.CharField(choices=[('INCEDIE', 'Incendie'), ('INONDATION', 'Inondation'), ('ACCIDENT', 'Accident'), ('CATASTROPHE_NATURELLE', 'Catastrophe naturelle'), ('URGENCE_MEDICALE', 'Urgence médicale'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50),
        ),
    ]
