# Generated by Django 5.2.11 on 2026-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_offre_materiel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crise',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
