# Generated by Django 5.2.11 on 2026-02-05 15:06

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_offre_materiel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/demandes/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='information',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/informations/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='offre',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/offres/', validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', validators=[core.validators.validate_image_file]),
        ),
    ]
