# Generated by Django 5.2.11 on 2026-03-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_crisis_radius_alter_crisis_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisis',
            options={'verbose_name_plural': 'Crises'},
        ),
    ]
