# Generated by Django 5.2.11 on 2026-03-03 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_demande_photo_alter_information_photo_and_more'),
        ('core', '0003_crise_auteur_crise_description_crise_photo_and_more'),
    ]

    operations = [
    ]
