# Generated by Django 5.2.11 on 2026-03-03 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_crisis_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisis',
            options={'verbose_name_plural': 'Crisis'},
        ),
    ]
