# Generated by Django 5.2.11 on 2026-02-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='crise',
            name='radius',
            field=models.IntegerField(default=10, help_text="Rayon d'impact en kilomètres"),
        ),
    ]
