# Generated by Django 5.2.11 on 2026-02-27 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crise_auteur_crise_description_crise_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='enable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_validé', to=settings.AUTH_USER_MODEL),
        ),
    ]
