# Generated by Django 5.2.10 on 2026-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='deletion_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='deletion_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='request',
            name='deletion_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
