# Generated by Django 5.2.12 on 2026-03-06 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_information_deletion_token_offer_deletion_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crisis',
            options={'verbose_name_plural': 'Crisis'},
        ),
    ]
