# Generated by Django 5.2.10 on 2026-02-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_merge"),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
