# Generated by Django 5.2.11 on 2026-02-13 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_crise_description'),
        ('core', '0004_utilisateur_code_postal_utilisateur_enable'),
    ]

    operations = [
    ]
