# Generated by Django 5.2.11 on 2026-03-03 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_utilisateur_code_postal_utilisateur_enable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crise',
            old_name='nom',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='crise',
            old_name='date_debut',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='crise',
            old_name='date_fin',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='crise',
            old_name='validateur',
            new_name='validator',
        ),
    ]
