# Generated by Django 5.2.11 on 2026-02-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_crise_radius'),
        ('core', '0005_merge_and_rename_to_english'),
    ]

    operations = [
    ]
