# Generated by Django 5.2.11 on 2026-02-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260213_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crise',
            name='radius',
            field=models.IntegerField(default=10),
        ),
    ]
