# Generated by Django 5.2.11 on 2026-03-03 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_crise_fields_to_english'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='validateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utilisateur_validé', to=settings.AUTH_USER_MODEL),
        ),
    ]
