# Generated by Django 5.2.11 on 2026-02-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_crise_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='crise',
            name='type',
            field=models.CharField(choices=[('INCEDIE', 'Incendie'), ('INONDATION', 'Inondation'), ('ACCIDENT', 'Accident'), ('CATASTROPHE_NATURELLE', 'Catastrophe naturelle'), ('URGENCE_MEDICALE', 'Urgence médicale'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50),
        ),
    ]
