# Generated by Django 5.2.16 on 2026-07-28 15:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_dossier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Besoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BesoinCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competences', to='core.besoin')),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='core.competence')),
            ],
        ),
    ]
