# Generated by Django 5.2.16 on 2026-07-28 20:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_besoin_affectationcompetence_besoincompetence'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTypeBesoin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_types', to='core.besoin')),
                ('request_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='besoins', to='core.requesttype')),
            ],
        ),
    ]
