# Generated by Django 5.2.16 on 2026-07-29 20:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_document_fichier_alter_document_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecherchePersonne',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('photo', models.ImageField(upload_to='recherches/')),
                ('source', models.CharField(choices=[('DOMICILE', 'Domicile'), ('EHPAD', 'EHPAD')], max_length=20)),
                ('ville', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ehpad_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ehpad_adresse', models.TextField(blank=True, null=True)),
                ('contact_nom', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_telephone', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('RECHERCHE', 'Recherche'), ('RETROUVEE', 'Retrouvée')], default='RECHERCHE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_retrouvee', models.DateTimeField(blank=True, null=True)),
                ('commentaire_retrouvee', models.TextField(blank=True, null=True)),
                ('vue_publique', models.BooleanField(default=True)),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recherches_personnes', to=settings.AUTH_USER_MODEL)),
                ('retrouve_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes_retrouvees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePersonneCommentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commentaire', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='core.recherchepersonne')),
            ],
        ),
    ]
