# Generated by Django 5.2.16 on 2026-07-30 07:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_affectationcompetence_recherchepersonne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherchepersonne',
            name='crise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recherches_personnes', to='core.crisis'),
        ),
        migrations.AlterField(
            model_name='besoincompetence',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='core.competence'),
        ),
        migrations.AlterField(
            model_name='dossier',
            name='competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossiers', to='core.competence'),
        ),
        migrations.CreateModel(
            name='RecherchePersonneHistorique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evenement', models.CharField(max_length=255)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='core.recherchepersonne')),
            ],
        ),
    ]
