# Generated by Django 5.2.16 on 2026-07-30 08:18

import django.db.models.deletion
import uuid

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_recherchepersonne_crise_and_more'),
    ]

    operations = []
