# Generated by Django 5.2.16 on 2026-07-30 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_affectationcompetence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recherchepersonne',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='recherches/'),
        ),
    ]
