# Generated by Django 5.2.16 on 2026-08-03 12:32

import core.models
import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_recherchepersonne_photo_affectationcompetence'),
    ]

    operations = [
        migrations.AddField(
            model_name='recherchepersonne',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recherchepersonne',
            name='statut',
            field=models.CharField(choices=[('RECHERCHE', 'Recherche'), ('RETROUVEE', 'Retrouvée'), ('ARCHIVEE', 'Archivée')], default='RECHERCHE', max_length=20),
        ),
        migrations.CreateModel(
            name='RecherchePersonneCommentairePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.ImageField(upload_to=core.models.secure_recherche_photo_path, validators=[core.validators.validate_image_file])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.recherchepersonnecommentaire')),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePersonnePhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fichier', models.ImageField(upload_to=core.models.secure_recherche_photo_path, validators=[core.validators.validate_image_file])),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.recherchepersonne')),
            ],
        ),
    ]
