# Generated by Django 5.2.16 on 2026-08-03 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_recherchepersonne_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecherchePersonneLectureHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LECTURE', 'Lecture'), ('ACQUITTEMENT', 'Acquittement')], max_length=20)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_lectures', to='core.recherchepersonne')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_lectures_recherches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecherchePersonneLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_lecture', models.DateTimeField(blank=True, null=True)),
                ('date_dernier_acquittement', models.DateTimeField(blank=True, null=True)),
                ('recherche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='core.recherchepersonne')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures_recherches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('recherche', 'utilisateur')},
            },
        ),
    ]
