# Generated by Django 5.2.16 on 2026-08-04 14:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_institution_institutiontype_roleoperationnel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='dossier',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE_DISTRIBUTION', 'En attente de distribution'), ('NOUVEAU', 'Nouveau'), ('EN_ATTENTE_AFFECTATION', "En attente d'affectation"), ('AFFECTE', 'Affecté'), ('EN_COURS', 'En cours'), ('RESOLU', 'Résolu'), ('CLOTURE', 'Clôturé')], default='NOUVEAU', max_length=50),
        ),
        migrations.CreateModel(
            name='AffectationRoleOperationnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_roles', to='core.competence')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_roles', to='core.institution')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='affectations', to='core.roleoperationnel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('objet_type', models.CharField(max_length=100)),
                ('objet_id', models.UUIDField(blank=True, null=True)),
                ('ancien_etat', models.JSONField(blank=True, null=True)),
                ('nouvel_etat', models.JSONField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('succes', models.BooleanField(default=True)),
                ('couleur', models.CharField(blank=True, max_length=20, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='core.auditaction')),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.crisis')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.institution')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='DelegationCompetence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='core.competence')),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delegations_competences', to='core.crisis')),
                ('institution_cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to='core.institution')),
                ('institution_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_emises', to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='DisponibiliteOperationnelle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disponible', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('affectation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.affectationroleoperationnel')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PointOperationnel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('obligatoire', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points_operationnels', to='core.crisis')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='points', to='core.pointtype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='affectationroleoperationnel',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'institution', 'competence', 'role'), name='uq_affectation_role'),
        ),
        migrations.AddConstraint(
            model_name='delegationcompetence',
            constraint=models.UniqueConstraint(fields=('institution_source', 'institution_cible', 'competence', 'crise'), name='uq_delegation_competence'),
        ),
        migrations.AddConstraint(
            model_name='disponibiliteoperationnelle',
            constraint=models.UniqueConstraint(condition=models.Q(('date_fin__isnull', True)), fields=('affectation',), name='uq_disponibilite_active'),
        ),
    ]
