# Generated by Django 6.1 on 2026-08-07 17:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auditaction_pointtype_alter_dossier_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionDomaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domaine', models.CharField(max_length=255, unique=True)),
                ('valide', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
            ],
        ),
        migrations.CreateModel(
            name='ContactInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fonction', models.CharField(blank=True, max_length=255)),
                ('contact_principal', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.institution')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('contact_principal', True)), fields=('institution',), name='uq_contact_principal_institution')],
            },
        ),
    ]
