# Generated by Django 5.2.17 on 2026-08-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_seed_audit_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pending_commune_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_commune_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_institution_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_institution_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
