# Generated by Django 5.2.17 on 2026-08-24 12:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_pending_institution_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointoperationnel',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_geres', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ImplicationInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_implication', models.CharField(choices=[('IMPLIQUE', 'Impliquée'), ('ACTEUR', 'Acteur opérationnel')], max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('crise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications', to='core.crisis')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implications_crises', to='core.institution')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implications_declarees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('crise', 'institution', 'type_implication'), name='uq_implication_crise_institution_type')],
            },
        ),
    ]
