# Generated by Django 5.2.17 on 2026-08-24 13:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_seed_point_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='zone',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
