# Generated by Django 5.2.17 on 2026-08-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_crisis_zone_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='type',
            field=models.CharField(choices=[('INCEDIE', 'Incendie'), ('INONDATION', 'Inondation'), ('ACCIDENT', 'Accident'), ('CATASTROPHE_NATURELLE', 'Catastrophe naturelle'), ('AUTRE', 'Autre')], default='AUTRE', max_length=50),
        ),
    ]
