# Generated by Django 5.2.17 on 2026-08-24 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_crisis_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='implicationinstitution',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text="Personne responsable/régulatrice pour l'institution sur cette crise.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implications_responsable', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='implicationinstitution',
            name='themes',
            field=models.ManyToManyField(blank=True, help_text="Besoins sur lesquels l'institution est à l'écoute pour cette crise.", related_name='implications_institutions', to='core.besoin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('AUT_LOCALE', 'Autorité locale'), ('SECOURS', 'Secours organisés'), ('REGULATEUR', 'Régulateur de crise'), ('UTIL_SIMPLE', 'Utilisateur')], default='UTIL_SIMPLE', max_length=20),
        ),
    ]
