# Generated by Django 5.2.17 on 2026-08-25 08:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_seed_besoins'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisponibiliteOffre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('creneau', models.CharField(choices=[('MATIN', 'Matin'), ('MIDI', 'Midi'), ('SOIR', 'Soir'), ('NUIT', 'Nuit')], max_length=10)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites', to='core.offer')),
            ],
            options={
                'ordering': ['date', 'creneau'],
                'constraints': [models.UniqueConstraint(fields=('offer', 'date', 'creneau'), name='uq_dispo_offre_date_creneau')],
            },
        ),
    ]
