# Generated by Django 5.2.17 on 2026-08-25 11:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_disponibiliteoffre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='hebergement_duree',
            field=models.CharField(blank=True, choices=[('TEMPORAIRE', 'Temporaire'), ('LONGUE_DUREE', 'Longue durée')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='materiel_type',
            field=models.CharField(blank=True, choices=[('CUVE', 'Cuve'), ('POMPE', 'Pompe'), ('ETUVE', 'Étuve'), ('CHAMBRE_FROIDE', 'Chambre froide'), ('REMORQUE', 'Remorque'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='numero_adeli_rpps',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='renouvelable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='soutien_type',
            field=models.CharField(blank=True, choices=[('PROFESSIONNEL', 'Professionnel de santé'), ('SECOURISTE', 'Secouriste (y compris santé mentale)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('PERSONNES', 'Transport de personnes'), ('MATERIEL', 'Transport de matériel')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offertype',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
