# Generated by Django 5.2.17 on 2026-08-25 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_offer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='demande',
            field=models.ForeignKey(blank=True, help_text="Demande d'aide à l'origine de ce dossier, si affecté depuis une demande.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='core.request'),
        ),
    ]
