# Generated by Django 5.2.17 on 2026-08-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_dossier_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
