# Generated by Django 5.2.17 on 2026-08-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_request_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationroleoperationnel',
            name='competence',
            field=models.ForeignKey(blank=True, help_text="Thème sur lequel cette personne opère. Peut rester vide juste après l'activation du compte, avant que les thèmes ne soient précisés.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affectations_roles', to='core.competence'),
        ),
    ]
