# Generated by Django 5.2.17 on 2026-08-26 02:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_seed_audit_actions_affectation_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='commune_code',
            field=models.CharField(blank=True, help_text="Code commune INSEE résolu à la saisie de l'adresse (autocomplete), utilisé pour le matching géographique avec les zones d'intervention des équipes.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='communes',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes commune INSEE (ex: ['38185']), plus précis que le département."),
        ),
        migrations.AddField(
            model_name='team',
            name='departements',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes département (ex: ['38', '73'])."),
        ),
        migrations.AddField(
            model_name='team',
            name='zone_precise',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Zone dessinée à la main, la plus précise des trois niveaux.', null=True, srid=4326),
        ),
    ]
