# Generated by Django 5.2.17 on 2026-08-26 19:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_request_commune_code_team_communes_team_departements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='azimuth',
            field=models.FloatField(blank=True, help_text="Azimut (0-360°, 0=Nord) capturé par la boussole du téléphone au moment de la photo — direction vers laquelle l'appareil pointait, pour situer ce que montre le signalement (ex: quel côté de la route est inondé).", null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
    ]
