# Generated by Django 5.2.17 on 2026-08-26 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_information_azimuth'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Catégorie parente si ce type est une précision d'un besoin plus large (ex: 'Groupe électrogène' sous 'Matériel', 'Anglais' sous 'Interprétariat / traduction').", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='core.requesttype'),
        ),
    ]
