# Generated by Django 5.2.17 on 2026-08-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_seed_besoins_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointoperationnel',
            name='date_fermeture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='date_ouverture',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='description',
            field=models.TextField(blank=True, help_text='Description du point (distincte de `commentaire`, qui reste des notes de suivi).', null=True),
        ),
    ]
