# Generated by Django 5.2.17 on 2026-08-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_seed_point_types_transit_regroupement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointoperationnel',
            name='competences_requises',
            field=models.ManyToManyField(blank=True, help_text='Compétences/thèmes nécessaires pour tenir ce point.', related_name='points_operationnels', to='core.competence'),
        ),
    ]
