# Generated by Django 5.2.17 on 2026-08-27 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_point_competences_requises'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointoperationnel',
            name='equipe',
            field=models.ForeignKey(blank=True, help_text='Équipe responsable de la tenue de ce point.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_operationnels', to='core.team'),
        ),
        migrations.CreateModel(
            name='DisponibilitePointEquipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('creneau', models.CharField(choices=[('MATIN', 'Matin'), ('MIDI', 'Midi'), ('SOIR', 'Soir'), ('NUIT', 'Nuit')], max_length=10)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_points', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilites_equipe', to='core.pointoperationnel')),
            ],
            options={
                'ordering': ['date', 'creneau'],
                'constraints': [models.UniqueConstraint(fields=('point', 'membre', 'date', 'creneau'), name='uq_dispo_point_equipe')],
            },
        ),
    ]
