# Generated by Django 5.2.17 on 2026-08-27 08:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_point_equipe_disponibilite'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('CUVE', 'Cuve'), ('POMPE', 'Pompe'), ('ETUVE', 'Étuve'), ('CHAMBRE_FROIDE', 'Chambre froide'), ('REMORQUE', 'Remorque'), ('AUTRE', 'Autre')], max_length=20)),
                ('nom', models.CharField(max_length=255)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('statut', models.CharField(choices=[('EN_TRANSIT', 'En transit'), ('SUR_PLACE', 'Sur place'), ('RETIRE', 'Retiré')], default='SUR_PLACE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='core.pointoperationnel')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_geres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_maj'],
            },
        ),
    ]
