# Generated by Django 5.2.17 on 2026-08-27 09:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_materiel_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegationcompetence',
            name='communes',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes commune INSEE (ex: ['38185']), plus précis que le département."),
        ),
        migrations.AddField(
            model_name='delegationcompetence',
            name='departements',
            field=models.JSONField(blank=True, default=list, help_text="Liste de codes département (ex: ['38', '73'])."),
        ),
        migrations.AddField(
            model_name='delegationcompetence',
            name='zone_precise',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Zone dessinée à la main, la plus précise des trois niveaux.', null=True, srid=4326),
        ),
    ]
