# Generated by Django 5.2.17 on 2026-08-27 10:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_seed_audit_action_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='zone_communes',
            field=models.JSONField(blank=True, default=list, help_text="Codes commune INSEE ajoutés à la zone de crise (ex: ['38185'])."),
        ),
        migrations.AddField(
            model_name='crisis',
            name='zone_departements',
            field=models.JSONField(blank=True, default=list, help_text="Codes département ajoutés à la zone de crise (ex: ['38', '73'])."),
        ),
        migrations.AddField(
            model_name='crisis',
            name='zone_secteurs',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, help_text='Union des contours de zone_departements/zone_communes, bufferisés de `radius` km.', null=True, srid=4326),
        ),
    ]
