# Generated by Django 5.2.17 on 2026-08-27 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_seed_institution_types_sante_police_municipale'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterielCatalogue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='materielpoint',
            name='type',
        ),
        migrations.AddField(
            model_name='materielpoint',
            name='niveau_stock',
            field=models.CharField(choices=[('NUL', 'Nul'), ('FAIBLE', 'Faible'), ('OK', 'OK'), ('EN_TROP', 'En trop')], default='NUL', max_length=10),
        ),
        migrations.AlterField(
            model_name='materielpoint',
            name='nom',
            field=models.CharField(blank=True, help_text='Précision libre optionnelle (ex: « 5kVA » pour un groupe électrogène).', max_length=255),
        ),
        migrations.AddField(
            model_name='materielpoint',
            name='item',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='core.materielcatalogue'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='materielpoint',
            constraint=models.UniqueConstraint(fields=('point', 'item'), name='uq_materielpoint_point_item'),
        ),
    ]
