# Generated by Django 5.2.17 on 2026-08-27 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_seed_materiel_catalogue'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrePresence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_personne', models.CharField(choices=[('EVACUE', 'Personne évacuée'), ('POMPIER', 'Pompier'), ('BENEVOLE_AUTRE_EQUIPE', "Bénévole d'une autre équipe"), ('AUTRE', 'Autre')], max_length=30)),
                ('nom', models.CharField(blank=True, max_length=255)),
                ('nombre', models.PositiveIntegerField(default=1)),
                ('date_arrivee', models.DateTimeField(auto_now_add=True)),
                ('date_depart', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registres_presences_enregistres', to=settings.AUTH_USER_MODEL)),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registre_presences', to='core.pointoperationnel')),
            ],
            options={
                'ordering': ['-date_arrivee'],
            },
        ),
    ]
