# Generated by Django 5.2.17 on 2026-08-27 14:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_registre_presence'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationPointBenevole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de confirmation'), ('CONFIRME', 'Confirmé'), ('DECLINE', 'Décliné')], default='EN_ATTENTE', max_length=15)),
                ('date_attendue', models.DateTimeField(help_text='Horaire auquel le bénévole est attendu sur le point.')),
                ('token_confirmation', models.CharField(max_length=64, unique=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_creees', to=settings.AUTH_USER_MODEL)),
                ('benevole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_points', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_points', to='core.offer')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations_benevoles', to='core.pointoperationnel')),
                ('point_transit', models.ForeignKey(blank=True, help_text="Point de transit obligatoire à indiquer au bénévole (route fermée, contrôle d'accès...).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.pointoperationnel')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='disponibilitepointequipe',
            name='affectation',
            field=models.ForeignKey(blank=True, help_text="Renseigné uniquement pour un créneau créé via le recrutement individuel depuis une offre d'aide — permet d'afficher son statut de confirmation. Nul pour un créneau auto-déclaré par un membre d'équipe (considéré confirmé d'office).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creneaux', to='core.affectationpointbenevole'),
        ),
    ]
