# Generated by Django 5.2.17 on 2026-08-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_affectation_point_benevole'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationcompetence',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='affectationpointbenevole',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='affectationroleoperationnel',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='contactinstitution',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='crisis',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='delegationcompetence',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='disponibiliteoffre',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='disponibiliteoperationnelle',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='disponibilitepointequipe',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='document',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='dossier',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='dossiercommentaire',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='dossierhistorique',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='dossierparticipant',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='implicationinstitution',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='information',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='institution',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='institutioncompetence',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='institutiondomaine',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='materielpoint',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='notification',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='offer',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonne',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonnecommentaire',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonnecommentairephoto',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonnehistorique',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonnelecture',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonnelecturehistorique',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='recherchepersonnephoto',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='registrepresence',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='request',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='team',
            name='environment',
            field=models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='demo_role',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Administrateur'), ('AUT_LOCALE', 'Autorité locale'), ('SECOURS', 'Secours organisés'), ('REGULATEUR', 'Régulateur de crise'), ('UTIL_SIMPLE', 'Utilisateur')], help_text='Rôle appliqué en zone de démonstration. Null = aucun accès à la démo. Réglé manuellement par un administrateur, jamais hérité de `type`.', max_length=20, null=True),
        ),
    ]
