# Generated by Django 5.2.17 on 2026-08-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_environment_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='competences',
            field=models.ManyToManyField(blank=True, related_name='offres', to='core.competence'),
        ),
    ]
