# Generated by Django 5.2.17 on 2026-08-28 08:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_repair_contact_principal_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='phone_offer',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='regulateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_regulees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_PREPARATION', 'En préparation'), ('EN_COURS', 'En cours'), ('TERMINEE', 'Terminée')], default='EN_PREPARATION', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('crise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='core.crisis')),
                ('equipes', models.ManyToManyField(blank=True, related_name='missions', to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='mission',
            field=models.ForeignKey(blank=True, help_text="Mission à laquelle ce dossier est rattaché, si affecté en tant que tel (affectation groupée de demandes). Une mission peut regrouper plusieurs équipes ; l'équipe précise pour CE dossier reste `equipe` ci-dessus.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='core.mission'),
        ),
    ]
