# Generated by Django 5.2.17 on 2026-08-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_mission_and_related_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='commune_code',
            field=models.CharField(blank=True, help_text="Code commune INSEE résolu à la saisie de l'adresse (autocomplete), symétrique à Request.commune_code — utilisé pour la vue mairie (filtrage par commune).", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='commune_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='commune_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
