# Generated by Django 5.2.17 on 2026-08-28 10:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_commune_scoping'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclarationSecurite',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_declarant', models.CharField(choices=[('PERSONNE_SEULE', 'Personne seule'), ('FAMILLE', 'Famille'), ('GROUPE', 'Groupe')], default='PERSONNE_SEULE', max_length=20)),
                ('nom_referent', models.CharField(max_length=80)),
                ('prenom_referent', models.CharField(max_length=60)),
                ('contact_referent', models.CharField(help_text='Email ou téléphone de la personne qui se présente/déclare — elle-même pour une personne seule, le référent désigné pour une famille ou un groupe.', max_length=255)),
                ('nombre_adultes', models.PositiveIntegerField(default=1)),
                ('nombre_enfants', models.PositiveIntegerField(default=0)),
                ('regime_alimentaire_specifique', models.BooleanField(default=False, help_text='Au moins une personne du groupe a un régime alimentaire spécifique (diabétique, végétarien...) — jamais une donnée de santé en soi. Se rapprocher des équipes sur place pour le préciser.')),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('centre_accueil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_securite', to='core.pointoperationnel')),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='declarations_securite', to='core.crisis')),
                ('declare_par', models.ForeignKey(blank=True, help_text='Opérateur ayant enregistré la déclaration (secrétariat du centre) — vide si auto-déclaration publique par la personne elle-même.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declarations_securite_enregistrees', to=settings.AUTH_USER_MODEL)),
                ('registre_presence', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declaration_securite', to='core.registrepresence')),
            ],
            options={
                'ordering': ['-date_declaration'],
            },
        ),
    ]
