# Generated by Django 5.2.17 on 2026-08-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_declarationsecurite'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='assigned_informations',
            field=models.ManyToManyField(blank=True, related_name='assigned_teams', to='core.information'),
        ),
    ]
