# Generated by Django 5.2.17 on 2026-08-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_team_assigned_informations'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationsecurite',
            name='situation',
            field=models.CharField(choices=[('RELOGE', 'En sécurité / relogé'), ('EN_CENTRE', "En centre d'accueil"), ('BESOIN_CENTRE', "En sécurité, cherche un centre d'accueil"), ('HORS_ZONE', 'En sécurité, hors zone')], default='RELOGE', max_length=20),
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='capacite_accueil',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
