# Generated by Django 5.2.17 on 2026-08-28 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_declarationsecurite_situation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='information',
            field=models.ForeignKey(blank=True, help_text="Signalement divers à l'origine de ce dossier, si affecté depuis un signalement.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='core.information'),
        ),
    ]
