# Generated by Django 5.2.17 on 2026-08-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_dossier_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='core.institution'),
        ),
    ]
