# Generated by Django 6.1 on 2026-08-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_derniere_position_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='ordre',
            field=models.PositiveIntegerField(default=0, help_text="Ordre d'intervention manuel au sein de son équipe (le plus petit en premier) — permet à un chef d'équipe de terrain d'organiser sa tournée."),
        ),
        migrations.AddField(
            model_name='dossier',
            name='priorite',
            field=models.CharField(choices=[('URGENTE', 'Urgente'), ('NORMALE', 'Normale'), ('BASSE', 'Basse')], default='NORMALE', help_text="Priorité de traitement, réglable par le chef d'équipe pour trier ses dossiers.", max_length=10),
        ),
    ]
