# Generated by Django 5.2.17 on 2026-08-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_dossier_priorite_ordre'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='diplome_secourisme',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='materiel_livraison',
            field=models.CharField(blank=True, choices=[('A_RECUPERER', 'À récupérer sur place'), ('LIVRAISON_POSSIBLE', 'Peut être déposé dans un centre de regroupement')], max_length=20, null=True),
        ),
    ]
