# Generated by Django 5.2.17 on 2026-08-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_offre_secourisme_livraison'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='confirmation_reglementaire',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='immatriculation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
