# Generated by Django 5.2.17 on 2026-08-29 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_offre_confirmation_immatriculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='core.mission'),
        ),
        migrations.AddField(
            model_name='team',
            name='mission_active',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes_actives', to='core.mission'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='crise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions', to='core.crisis'),
        ),
    ]
