# Generated by Django 5.2.17 on 2026-08-29 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_equipe_mission_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='materiel_catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres', to='core.materielcatalogue'),
        ),
        migrations.AddField(
            model_name='offer',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='unite',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
