# Generated by Django 5.2.17 on 2026-08-29 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_offre_materiel_catalogue_quantite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionMateriel',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fournisseur_nom', models.CharField(blank=True, max_length=140)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('unite', models.CharField(default='unité', max_length=20)),
                ('statut', models.CharField(choices=[('EN_TRANSIT', 'En transit'), ('SUR_PLACE', 'Sur place'), ('RETIRE', 'Retiré')], default='SUR_PLACE', max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_reception', models.DateTimeField(auto_now_add=True)),
                ('materiel_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='core.materielpoint')),
                ('offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_materiel', to='core.offer')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_reception'],
            },
        ),
    ]
