# Generated by Django 5.2.17 on 2026-08-30 11:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_contribution_materiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='institution_delegataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_deleguees', to='core.institution'),
        ),
        migrations.CreateModel(
            name='TeamDelegation',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_equipes_recues', to='core.institution')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='core.team')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
    ]
