# Generated by Django 5.2.17 on 2026-08-30 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_fix_incendie_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='equipe_parente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_equipes', to='core.team'),
        ),
    ]
