# Generated by Django 5.2.17 on 2026-08-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_team_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='groupe_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='organisation_nom',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
