# Generated by Django 5.2.17 on 2026-08-30 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_offre_depot_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementRessource',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de confirmation'), ('CONFIRME', 'Confirmé'), ('DECLINE', 'Décliné'), ('EN_TRANSIT', 'En transit'), ('ARRIVE', 'Arrivé / à disposition')], default='EN_ATTENTE', max_length=20)),
                ('token_confirmation', models.CharField(max_length=64, unique=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_transit', models.DateTimeField(blank=True, null=True)),
                ('date_arrivee', models.DateTimeField(blank=True, null=True)),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='core.offer')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements_ressources', to='core.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
