# Generated by Django 5.2.17 on 2026-08-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_engagement_ressource'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='presence_physique',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
