# Generated by Django 5.2.17 on 2026-08-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_offre_presence_physique'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='actif',
            field=models.BooleanField(default=True, help_text="False = désactivée par son auteur ou un acteur institutionnel — reste visible dans l'historique jusqu'à la clôture de la crise rattachée, où elle est définitivement purgée. Ne masque jamais les signalements actifs."),
        ),
        migrations.AddField(
            model_name='offer',
            name='actif',
            field=models.BooleanField(default=True, help_text="False = désactivée par son auteur ou un acteur institutionnel — reste visible dans l'historique jusqu'à la clôture de la crise rattachée, où elle est définitivement purgée. Ne masque jamais les offres actives."),
        ),
        migrations.AddField(
            model_name='request',
            name='actif',
            field=models.BooleanField(default=True, help_text="False = désactivée par son auteur ou un acteur institutionnel — reste visible dans l'historique jusqu'à la clôture de la crise rattachée, où elle est définitivement purgée. Ne masque jamais les demandes actives."),
        ),
        migrations.AddField(
            model_name='team',
            name='actif',
            field=models.BooleanField(default=True, help_text="False = désactivée par un acteur institutionnel — reste dans l'historique indéfiniment (une équipe peut couvrir plusieurs crises), pas de purge automatique à la clôture d'une crise contrairement à Offer/Request/Information."),
        ),
    ]
