# Generated by Django 5.2.17 on 2026-09-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_seed_audit_actions_desactivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='actif',
            field=models.BooleanField(default=True),
        ),
    ]
