# Generated by Django 5.2.17 on 2026-09-01 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_seed_institution_type_sdis'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossier',
            name='date_signalement_important',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossier',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
