# Generated by Django 5.2.17 on 2026-09-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0089_seed_institution_type_aasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationpointbenevole',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de confirmation'), ('EN_VALIDATION', 'En attente de validation par le régulateur'), ('CONFIRME', 'Confirmé'), ('DECLINE', 'Décliné')], default='EN_ATTENTE', max_length=15),
        ),
    ]
