# Generated by Django 5.2.17 on 2026-09-01 13:12

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_affectation_en_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationsecurite',
            name='commune_code',
            field=models.CharField(blank=True, help_text="Code commune INSEE résolu à la saisie de l'adresse (autocomplete), même usage qu'Information.commune_code.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='declarationsecurite',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='declarationsecurite',
            name='crise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='declarations_securite', to='core.crisis'),
        ),
    ]
