# Generated by Django 5.2.17 on 2026-09-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_seed_role_operationnel_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='cuve_contenu',
            field=models.CharField(blank=True, choices=[('EAU', 'Eau'), ('CARBURANT', 'Carburant')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='transport_animaux_precision',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='materiel_type',
            field=models.CharField(blank=True, choices=[('CUVE', 'Cuve'), ('POMPE', 'Pompe'), ('ETUVE', 'Étuve'), ('CHAMBRE_FROIDE', 'Chambre froide'), ('REMORQUE', 'Remorque'), ('ENGIN_TRACTE', 'Engin/machine tracté(e) (bulldozer à lame, broyeur, déchaumeur, cover crop...)'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='transport_type',
            field=models.CharField(blank=True, choices=[('PERSONNES', 'Transport de personnes'), ('MATERIEL', 'Transport de matériel'), ('ANIMAUX', "Transport d'animaux")], max_length=20, null=True),
        ),
    ]
