# Generated by Django 5.2.17 on 2026-09-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_besoins_cuve_engin_tracte_transport_animaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielcatalogue',
            name='categorie',
            field=models.CharField(blank=True, choices=[('ENGIN', 'Engin agricole / chantier / spécial')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='materiel_type',
            field=models.CharField(blank=True, choices=[('CUVE', 'Cuve'), ('POMPE', 'Pompe'), ('ETUVE', 'Étuve'), ('CHAMBRE_FROIDE', 'Chambre froide'), ('REMORQUE', 'Remorque'), ('AUTRE', 'Autre')], max_length=20, null=True),
        ),
    ]
