# Generated by Django 5.2.17 on 2026-09-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_seed_engins_agricoles_chantiers_speciaux'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='acces_etage',
            field=models.CharField(blank=True, choices=[('ESCALIER', 'Escalier'), ('ASCENSEUR', 'Ascenseur')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='animaux_acceptes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='capacite_adultes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='capacite_enfants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='loyer_montant_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='loyer_montant_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='niveau_logement',
            field=models.CharField(blank=True, choices=[('PLAIN_PIED', 'Plain-pied'), ('ETAGE', 'Étage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='nombre_chambres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='nombre_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pmr_compatible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='type_logement',
            field=models.CharField(blank=True, choices=[('MAISON', 'Maison'), ('APPARTEMENT', 'Appartement'), ('STUDIO', 'Studio'), ('COLOCATION', 'Colocation'), ('CHAMBRE', 'Chambre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='type_loyer',
            field=models.CharField(blank=True, choices=[('GRATUIT', 'Gratuit'), ('NEGOCIE', 'Loyer négocié (du fait de la situation)'), ('MARCHE', 'Loyer au prix du marché')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='acces_etage',
            field=models.CharField(blank=True, choices=[('ESCALIER', 'Escalier'), ('ASCENSEUR', 'Ascenseur')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='animaux_acceptes',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='capacite_adultes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='capacite_enfants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='hebergement_duree',
            field=models.CharField(blank=True, choices=[('TEMPORAIRE', 'Temporaire'), ('LONGUE_DUREE', 'Longue durée')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='jardin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='loyer_montant_max',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='loyer_montant_min',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='niveau_logement',
            field=models.CharField(blank=True, choices=[('PLAIN_PIED', 'Plain-pied'), ('ETAGE', 'Étage')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='nombre_chambres',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='nombre_pieces',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='pmr_compatible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='request',
            name='type_logement',
            field=models.CharField(blank=True, choices=[('MAISON', 'Maison'), ('APPARTEMENT', 'Appartement'), ('STUDIO', 'Studio'), ('COLOCATION', 'Colocation'), ('CHAMBRE', 'Chambre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='type_loyer',
            field=models.CharField(blank=True, choices=[('GRATUIT', 'Gratuit'), ('NEGOCIE', 'Loyer négocié (du fait de la situation)'), ('MARCHE', 'Loyer au prix du marché')], max_length=20, null=True),
        ),
    ]
