# Generated by Django 5.2.17 on 2026-09-02 02:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_hebergement_details_offre_et_demande'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='zone_recherche_communes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='request',
            name='zone_recherche_rayon_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='commune_code',
            field=models.CharField(blank=True, help_text="Code commune INSEE résolu à la saisie de l'adresse (autocomplete), utilisé pour le matching géographique avec les zones d'intervention des équipes. Pour une demande d'hébergement : première commune de zone_recherche_communes.", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
