# Generated by Django 5.2.17 on 2026-09-02 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_request_zone_recherche_hebergement'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='reponse_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='core.besoin'),
        ),
        migrations.CreateModel(
            name='OfferMessage',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('auteur_equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_offres_envoyes', to=settings.AUTH_USER_MODEL)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.offer')),
            ],
            options={
                'ordering': ['date_creation'],
            },
        ),
    ]
