# Generated by Django 5.2.17 on 2026-09-02 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_equipe_themes_et_messagerie_offre'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointoperationnel',
            name='equipes_gestion',
            field=models.ManyToManyField(blank=True, help_text='Équipes supplémentaires tenant ce point (par spécialité), en plus de `equipe`.', related_name='points_geres_specialite', to='core.team'),
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='equipes_ravitaillement',
            field=models.ManyToManyField(blank=True, help_text='Équipes de terrain ravitaillées par ce point (repas, repos, carburant...).', related_name='points_ravitaillement', to='core.team'),
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='responsables',
            field=models.ManyToManyField(blank=True, help_text='Responsables supplémentaires de ce point, en plus de `responsable`.', related_name='points_responsable_secondaire', to=settings.AUTH_USER_MODEL),
        ),
    ]
