# Generated by Django 5.2.17 on 2026-09-03 11:58

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_point_equipes_gestion_ravitaillement_responsables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('communes', models.JSONField(blank=True, default=list, help_text="Liste de codes commune INSEE (ex: ['38185']).")),
                ('zone_precise', django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Zone dessinée à la main, plus précise que la liste de communes.', null=True, srid=4326)),
                ('actif', models.BooleanField(default=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='zones', to='core.institution')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('equipes', models.ManyToManyField(blank=True, related_name='plans', to='core.team')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='core.institution')),
                ('points', models.ManyToManyField(blank=True, related_name='plans', to='core.pointoperationnel')),
                ('zones', models.ManyToManyField(blank=True, related_name='plans', to='core.zone')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='pointoperationnel',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_operationnels', to='core.zone'),
        ),
        migrations.AddField(
            model_name='team',
            name='zone_principale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipes', to='core.zone'),
        ),
    ]
