# Generated by Django 5.2.17 on 2026-09-03 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_seed_role_operationnel_referent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, max_length=255, null=True)),
                ('centre_latitude', models.FloatField(blank=True, null=True)),
                ('centre_longitude', models.FloatField(blank=True, null=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PointCommune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='points', to='core.commune')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('lat', 'lon'), name='uq_point_commune')],
            },
        ),
    ]
