# Generated by Django 5.2.17 on 2026-09-03 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_commune_geo_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='derniere_tentative',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pointcommune',
            name='derniere_tentative',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
