# Generated by Django 5.2.17 on 2026-09-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_commune_retry_cooldown'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='departement_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='epci_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='population',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='commune_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='departement_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='epci_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
    ]
