# Generated by Django 5.2.17 on 2026-09-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_seed_audit_action_envoi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='departement_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='epci_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='region_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='secteur_override',
            field=models.CharField(blank=True, choices=[('commune', 'Communal'), ('epci', 'Intercommunal (EPCI)'), ('departement', 'Départemental'), ('region', 'Régional'), ('national', 'National')], help_text='Force le niveau de secteur (vue_secteur) pour cette institution, quel que soit son type — usage test uniquement, laisser vide sinon.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
