# Generated by Django 5.2.17 on 2026-09-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_commune_region_code_institution_departement_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='secteur_niveau_effectif',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='secteur_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
