# Generated by Django 5.2.17 on 2026-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_seed_audit_action_journal_bord'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='departement_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='epci_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
