# Generated by Django 5.2.17 on 2026-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_backfill_request_secteur_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='derniere_tentative_risques',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commune',
            name='risques_territoire',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
