# Generated by Django 5.2.17 on 2026-09-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_commune_risques_territoire'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielpoint',
            name='nombre_places_assises',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='nombre_places_assises',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='nombre_places_assises',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
