# Generated by Django 5.2.17 on 2026-09-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_seed_audit_action_import_liste'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationsecurite',
            name='departement_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='declarationsecurite',
            name='epci_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='declarationsecurite',
            name='region_code',
            field=models.CharField(blank=True, db_index=True, max_length=3, null=True),
        ),
    ]
