# Generated by Django 5.2.17 on 2026-09-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0118_declarationsecurite_departement_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalcollectivite',
            name='crise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.crisis'),
        ),
    ]
