# Generated by Django 5.2.17 on 2026-09-07 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_backfill_journal_collectivite_crise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalcollectivite',
            name='crise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='core.crisis'),
        ),
    ]
