# Generated by Django 5.2.17 on 2026-09-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_alter_journalcollectivite_crise'),
    ]

    operations = [
        migrations.AddField(
            model_name='competence',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_competences', to='core.competence'),
        ),
    ]
