# Generated by Django 5.2.17 on 2026-09-08 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_competence_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='commune_code_postal',
            field=models.CharField(blank=True, help_text="Code postal de la commune de l'institution — utile pour distinguer des communes homonymes, jamais recalculé automatiquement.", max_length=10, null=True),
        ),
    ]
