# Generated by Django 5.2.17 on 2026-09-08 17:19

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_institution_commune_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectationroleoperationnel',
            name='responsabilite',
            field=models.CharField(blank=True, help_text='Intitulé libre du périmètre de responsabilité (ex: "Coordination hébergement secteur nord") — distinct du rôle (fonction) et du thème (compétence).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='affectationroleoperationnel',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_roles', to='core.zone'),
        ),
        migrations.AddField(
            model_name='affectationroleoperationnel',
            name='zone_precise',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, help_text='Dessin optionnel, propre à cette affectation — indépendant de Zone.zone_precise si `zone` est aussi renseignée (ex: un périmètre plus fin que la zone cataloguée).', null=True, srid=4326),
        ),
    ]
