# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_affectation_role_zone_responsabilite'),
    ]

    operations = [
        migrations.AddField(
            model_name='implicationinstitution',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], default='VALIDEE', max_length=20),
        ),
    ]
