# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_implicationinstitution_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='crise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.crisis'),
        ),
    ]
