# Generated by Django 5.2.17 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_notification_crise'),
    ]

    operations = [
        migrations.AddField(
            model_name='declarationsecurite',
            name='ages_enfants',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
