# Generated by Django 5.2.17 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_declarationsecurite_ages_enfants'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinstitution',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='core.zone'),
        ),
    ]
