# Generated by Django 5.2.17 on 2026-09-08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0128_contactinstitution_zone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanMissionModele',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('URGENTE', 'Urgente'), ('NORMALE', 'Normale'), ('BASSE', 'Basse')], default='NORMALE', max_length=10)),
                ('equipe', models.ForeignKey(help_text="Doit être l'une des équipes du plan — vérifié à la création (voir PlanMissionModeleViewSet.perform_create), pas de contrainte DB (l'équipe peut être ajoutée au plan après coup).", on_delete=django.db.models.deletion.CASCADE, related_name='missions_modeles_plan', to='core.team')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions_modeles', to='core.plan')),
                ('referent', models.ForeignKey(blank=True, help_text="Personne désignée pour cette mission à l'activation (pas forcément un membre de l'équipe) — optionnel.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='missions_modeles_referent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['titre'],
            },
        ),
    ]
