# Generated by Django 5.2.17 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0130_mission_modele_origine'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='ancien_sapeur_pompier',
            field=models.BooleanField(default=False),
        ),
    ]
