# Generated by hand (voir CLAUDE session) — même patron que 0096 (catégorie du catalogue
# matériel) : la modification du kwarg choices= d'un champ existant nécessite une AlterField
# explicite pour que `makemigrations --check --dry-run` ne détecte plus de diff.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_offer_ancien_sapeur_pompier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materielcatalogue',
            name='categorie',
            field=models.CharField(
                blank=True,
                choices=[
                    ('ENGIN', 'Engin agricole / chantier / spécial'),
                    ('NETTOYAGE', 'Nettoyage et remise en état'),
                    ('POMPAGE', "Pompage et évacuation d'eau"),
                    ('DEBLAI_MANUTENTION', 'Déblaiement et manutention'),
                    ('ENERGIE_ECLAIRAGE', 'Énergie et éclairage'),
                    ('PROTECTION_BATIMENTS', 'Protection des bâtiments'),
                    ('OUTILLAGE_TERRAIN', "Outillage et équipement de terrain"),
                    ('PROTECTION_INDIVIDUELLE', 'Protection individuelle'),
                    ('ACCUEIL_HEBERGEMENT', "Accueil et hébergement d'urgence"),
                    ('DIVERS', 'Divers / consommables'),
                ],
                max_length=30, null=True,
            ),
        ),
        migrations.AddField(
            model_name='pointtype',
            name='categories_materiel_exclues',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
