# Generated by Django 5.2.17 on 2026-09-10 10:22

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_seed_materiel_stock_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crisis',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.secure_crisis_photo_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(max_length=255, upload_to=core.models.secure_document_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='information',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.secure_information_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.secure_offre_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='offerphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to=core.models.secure_offre_galerie_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='recherchepersonne',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.secure_recherche_personne_photo_path),
        ),
        migrations.AlterField(
            model_name='recherchepersonnecommentairephoto',
            name='fichier',
            field=models.ImageField(max_length=255, upload_to=core.models.secure_recherche_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='recherchepersonnephoto',
            name='fichier',
            field=models.ImageField(max_length=255, upload_to=core.models.secure_recherche_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.secure_demande_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='requestphoto',
            name='image',
            field=models.ImageField(max_length=255, upload_to=core.models.secure_demande_galerie_photo_path, validators=[core.validators.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=core.models.secure_user_photo_path, validators=[core.validators.validate_image_file]),
        ),
    ]
