# Generated by Django 5.2.17 on 2026-09-10 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_secure_upload_filenames'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_besoins', to='core.besoin'),
        ),
    ]
