# Generated by Django 5.2.17 on 2026-09-10 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0135_besoin_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='materielcatalogue',
            name='actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='materielcatalogue',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_materiels', to='core.materielcatalogue'),
        ),
    ]
