# Generated by Django 5.2.17 on 2026-09-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0136_materielcatalogue_actif_materielcatalogue_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='accompagne',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='nombre_accompagnants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
