# Generated by Django 5.2.17 on 2026-09-10 15:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0137_offer_accompagne_offer_nombre_accompagnants'),
    ]

    operations = [
        migrations.AddField(
            model_name='besoin',
            name='nature',
            field=models.CharField(blank=True, choices=[('COMPETENCE', 'Compétence (savoir-faire humain)'), ('MATERIEL', 'Matériel'), ('MIXTE', 'Compétence et matériel')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='BesoinMateriel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('besoin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiels', to='core.besoin')),
                ('materiel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='besoins', to='core.materielcatalogue')),
            ],
        ),
    ]
