# Generated by Django 5.2.17 on 2026-09-11 05:20

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0141_meshcore_poc'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagemeshlog',
            name='equipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_meshcore', to='core.team'),
        ),
        migrations.CreateModel(
            name='CanalMeshCore',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('cle_partagee_hex', models.CharField(blank=True, max_length=64, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_meshcore', to='core.crisis')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canaux_meshcore', to='core.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageCanalMeshCore',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ENTRANT', 'Reçu du mesh'), ('SORTANT', 'Envoyé vers le mesh')], max_length=10)),
                ('contact_pubkey_hex', models.CharField(blank=True, max_length=64, null=True)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'envoi"), ('ENVOYE', 'Envoyé'), ('RECU', 'Reçu'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=12)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.canalmeshcore')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_canal_meshcore_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RelaisMeshCore',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('pubkey_hex', models.CharField(blank=True, max_length=64, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relais_meshcore', to='core.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
