# Generated by Django 5.2.17 on 2026-09-10 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_add_photo_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnonMeshCore',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('connexion_type', models.CharField(choices=[('TCP', 'TCP (réseau)'), ('SERIE', 'Série (USB)'), ('BLE', 'Bluetooth (BLE)')], max_length=10)),
                ('tcp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('tcp_port', models.PositiveIntegerField(blank=True, default=5000, null=True)),
                ('serie_device', models.CharField(blank=True, help_text='ex: /dev/ttyUSB0', max_length=255, null=True)),
                ('ble_adresse', models.CharField(blank=True, max_length=64, null=True)),
                ('pubkey_hex', models.CharField(blank=True, help_text='Renseigné par le service-pont après la première connexion réussie.', max_length=64, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('dernier_etat', models.CharField(blank=True, help_text='Rapporté par le service-pont : CONNECTE / DECONNECTE / ERREUR.', max_length=20, null=True)),
                ('derniere_erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compagnons_meshcore', to='core.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageMeshLog',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ENTRANT', 'Reçu du mesh'), ('SORTANT', 'Envoyé vers le mesh')], max_length=10)),
                ('contact_pubkey_hex', models.CharField(help_text='Clé publique du correspondant (émetteur si entrant, destinataire si sortant).', max_length=64)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'envoi"), ('ENVOYE', 'Envoyé'), ('RECU', 'Reçu'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=12)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('compagnon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.compagnonmeshcore')),
                ('expediteur', models.ForeignKey(blank=True, help_text='Résolu via NoeudMeshUtilisateur quand connu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_meshcore_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoeudMeshUtilisateur',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pubkey_hex', models.CharField(max_length=64, unique=True)),
                ('nom_noeud', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_association', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noeuds_meshcore', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
