# Generated by Django 5.2.17 on 2026-09-11 07:25

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0142_meshcore_canaux_relais'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeshCore',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pubkey_hex', models.CharField(max_length=64)),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('type_contact', models.CharField(choices=[('INCONNU', 'Inconnu'), ('COMPANION', 'Companion'), ('REPEATER', 'Répéteur'), ('ROOM', 'Room server'), ('SENSOR', 'Capteur')], default='INCONNU', max_length=12)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('dernier_advert', models.DateTimeField(blank=True, null=True)),
                ('date_synchronisation', models.DateTimeField(auto_now=True)),
                ('compagnon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.compagnonmeshcore')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('compagnon', 'pubkey_hex'), name='uq_contact_meshcore_compagnon_pubkey')],
            },
        ),
    ]
