# Generated by Django 5.2.17 on 2026-09-11 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0145_meshcore_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmeshcore',
            name='canal_idx',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='canalmeshcore',
            name='compagnon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_provisionnes', to='core.compagnonmeshcore'),
        ),
        migrations.AddField(
            model_name='canalmeshcore',
            name='equipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canal_meshcore', to='core.team'),
        ),
    ]
