# Generated by Django 5.2.17 on 2026-09-11 19:55

from django.db import migrations, models


def dedupliquer_relais_par_pubkey(apps, schema_editor):
    """Nettoie les doublons créés par l'ancien bouton "Importer" manuel (aucune protection
    anti-doublon avant ce correctif — un répéteur détecté pouvait être importé plusieurs fois,
    créant une nouvelle ligne identique à chaque clic) avant de rendre pubkey_hex unique.
    Garde la ligne la plus ancienne, supprime les autres."""
    RelaisMeshCore = apps.get_model('core', 'RelaisMeshCore')
    vus = {}
    a_supprimer = []
    for relais in RelaisMeshCore.objects.filter(pubkey_hex__isnull=False).order_by('date_creation'):
        if relais.pubkey_hex in vus:
            a_supprimer.append(relais.id)
        else:
            vus[relais.pubkey_hex] = relais.id
    if a_supprimer:
        RelaisMeshCore.objects.filter(id__in=a_supprimer).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_canal_meshcore_equipe'),
    ]

    operations = [
        migrations.RunPython(dedupliquer_relais_par_pubkey, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='relaismeshcore',
            name='pubkey_hex',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
