# Generated by Django 5.2.17 on 2026-09-13 12:09

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0146_compagnon_meshcore_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnonMeshtastic',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('node_num', models.PositiveIntegerField(help_text="Identifiant 32 bits de cette identité logicielle sur le mesh Meshtastic (choisi à la création, pas dérivé d'un matériel).", unique=True)),
                ('long_name', models.CharField(blank=True, max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=4)),
                ('broker_host', models.CharField(default='mqtt.gaulix.fr', max_length=255)),
                ('broker_port', models.PositiveIntegerField(default=1883)),
                ('topic_racine', models.CharField(default='msh/EU_868', max_length=100)),
                ('principal', models.BooleanField(default=False)),
                ('actif', models.BooleanField(default=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('dernier_etat', models.CharField(blank=True, help_text='Rapporté par le service-pont : CONNECTE / DECONNECTE / ERREUR.', max_length=20, null=True)),
                ('derniere_erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compagnons_meshtastic', to='core.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CanalMeshtastic',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('psk_hex', models.CharField(blank=True, max_length=64, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('crise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_meshtastic', to='core.crisis')),
                ('equipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canal_meshtastic', to='core.team')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canaux_meshtastic', to='core.institution')),
                ('compagnon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux', to='core.compagnonmeshtastic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageCanalMeshtastic',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ENTRANT', 'Reçu du mesh'), ('SORTANT', 'Envoyé vers le mesh')], max_length=10)),
                ('contact_node_num', models.PositiveIntegerField(blank=True, null=True)),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'envoi"), ('ENVOYE', 'Envoyé'), ('RECU', 'Reçu'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=12)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.canalmeshtastic')),
                ('expediteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_canal_meshtastic_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageMeshtasticLog',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('ENTRANT', 'Reçu du mesh'), ('SORTANT', 'Envoyé vers le mesh')], max_length=10)),
                ('contact_node_num', models.PositiveIntegerField(help_text='Node num du correspondant (émetteur si entrant, destinataire si sortant).')),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'envoi"), ('ENVOYE', 'Envoyé'), ('RECU', 'Reçu'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=12)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_envoi', models.DateTimeField(blank=True, null=True)),
                ('canal', models.ForeignKey(blank=True, help_text='Canal dont la PSK a servi à chiffrer ce DM.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_dm', to='core.canalmeshtastic')),
                ('compagnon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.compagnonmeshtastic')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_meshtastic', to='core.team')),
                ('expediteur', models.ForeignKey(blank=True, help_text='Résolu via NoeudUtilisateurMeshtastic quand connu.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_meshtastic_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoeudUtilisateurMeshtastic',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_num', models.PositiveIntegerField(unique=True)),
                ('nom_noeud', models.CharField(blank=True, max_length=100)),
                ('actif', models.BooleanField(default=True)),
                ('date_association', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noeuds_meshtastic', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactMeshtastic',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_num', models.PositiveIntegerField()),
                ('long_name', models.CharField(blank=True, max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=4)),
                ('hardware_model', models.CharField(blank=True, max_length=40, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('dernier_advert', models.DateTimeField(blank=True, null=True)),
                ('date_synchronisation', models.DateTimeField(auto_now=True)),
                ('compagnon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='core.compagnonmeshtastic')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('compagnon', 'node_num'), name='uq_contact_meshtastic_compagnon_node_num')],
            },
        ),
    ]
