# Generated by Django 5.2.17 on 2026-09-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0147_meshtastic_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnonmeshtastic',
            name='node_num',
            field=models.PositiveBigIntegerField(help_text="Identifiant 32 bits de cette identité logicielle sur le mesh Meshtastic (choisi à la création, pas dérivé d'un matériel).", unique=True),
        ),
        migrations.AlterField(
            model_name='contactmeshtastic',
            name='node_num',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='messagecanalmeshtastic',
            name='contact_node_num',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messagemeshtasticlog',
            name='contact_node_num',
            field=models.PositiveBigIntegerField(help_text='Node num du correspondant (émetteur si entrant, destinataire si sortant).'),
        ),
        migrations.AlterField(
            model_name='noeudutilisateurmeshtastic',
            name='node_num',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
