# Generated by Django 5.2.17 on 2026-09-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0148_meshtastic_node_num_bigint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compagnonmeshtastic',
            name='topic_racine',
            field=models.CharField(default='Traitement/msh/EU_868', max_length=100),
        ),
    ]
