# Generated by Django 5.2.17 on 2026-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0149_alter_compagnonmeshtastic_topic_racine'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='x25519_private_key_hex',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='contactmeshtastic',
            name='public_key_hex',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
