# Generated by Django 5.2.17 on 2026-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0150_meshtastic_pkc'),
    ]

    operations = [
        migrations.AddField(
            model_name='canalmeshtastic',
            name='principal',
            field=models.BooleanField(default=False),
        ),
    ]
