# Generated by Django 5.2.17 on 2026-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0153_canal_meshtastic_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='chiffrement_supporte',
            field=models.BooleanField(default=False, help_text="Décoché par défaut (cas Gaulix) : le pont force alors l'envoi en clair pour ce broker, quel que soit le canal/la clé configurés."),
        ),
    ]
