# Generated by Django 5.2.17 on 2026-09-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0154_compagnon_meshtastic_chiffrement_supporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='mqtt_use_tls',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
