# Generated by Django 5.2.17 on 2026-09-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0155_compagnon_meshtastic_mqtt_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='connexion_type',
            field=models.CharField(choices=[('MQTT', 'Broker MQTT (réseau tiers, ex: Gaulix)'), ('TCP', 'Connexion locale directe (réseau, sans internet)')], default='MQTT', max_length=10),
        ),
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='tcp_host',
            field=models.CharField(blank=True, help_text='IP/hostname du vrai appareil (mode TCP local uniquement).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='tcp_port',
            field=models.PositiveIntegerField(blank=True, default=4403, null=True),
        ),
    ]
