# Generated by Django 5.2.17 on 2026-09-17 04:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0156_compagnon_meshtastic_tcp_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeMeshCore',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_commande', models.CharField(choices=[('ADVERT', 'Advert (annonce de présence)'), ('FLOOD_ADVERT', 'Flood advert (annonce propagée)')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EXECUTEE', 'Exécutée'), ('ECHEC', 'Échec')], default='EN_ATTENTE', max_length=12)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_execution', models.DateTimeField(blank=True, null=True)),
                ('compagnon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.compagnonmeshcore')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
