# Generated by Django 5.2.17 on 2026-09-17 10:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0157_commande_meshcore'),
    ]

    operations = [
        migrations.CreateModel(
            name='JetonEnrolementSatellite',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jeton', models.CharField(max_length=64, unique=True)),
                ('expiration', models.DateTimeField()),
                ('utilise', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jetons_enrolement_satellite', to='core.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Satellite',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('profil', models.CharField(choices=[('GW', 'Passerelle uniquement'), ('FULL', 'Suite complète')], max_length=4)),
                ('statut_enrolement', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('APPROUVE', 'Approuvé'), ('REVOQUE', 'Révoqué')], default='EN_ATTENTE', max_length=12)),
                ('dernier_contact', models.DateTimeField(blank=True, null=True)),
                ('version_logicielle', models.CharField(blank=True, max_length=50)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('compte_service', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satellite', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellites', to='core.institution')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
