# Generated by Django 5.2.17 on 2026-09-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0158_satellite'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnonmeshtastic',
            name='serie_device',
            field=models.CharField(blank=True, help_text='ex: /dev/ttyUSB0 (mode SERIE uniquement).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='compagnonmeshtastic',
            name='connexion_type',
            field=models.CharField(choices=[('MQTT', 'Broker MQTT (réseau tiers, ex: Gaulix)'), ('TCP', 'Connexion locale directe (réseau, sans internet)'), ('SERIE', 'Connexion série (USB, sans internet)')], default='MQTT', max_length=10),
        ),
    ]
