# Generated by Django 5.2.17 on 2026-09-18 04:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0159_meshtastic_serie'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvenementSynchronisation',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modele', models.CharField(choices=[('Dossier', 'Dossier'), ('DossierCommentaire', 'Commentaire de dossier'), ('DossierHistorique', 'Historique de dossier'), ('DeclarationSecurite', 'Déclaration de sécurité'), ('Mission', 'Mission'), ('MessageMeshLog', 'Message mesh')], max_length=30)),
                ('objet_id', models.UUIDField()),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification')], max_length=15)),
                ('payload', models.JSONField()),
                ('version_de_base', models.DateTimeField(blank=True, null=True)),
                ('auteur_local_email', models.CharField(blank=True, max_length=255)),
                ('auteur_local_nom', models.CharField(blank=True, max_length=255)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('etat', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('SYNCHRONISE', 'Synchronisé'), ('CONFLIT', 'En conflit — arbitrage requis'), ('ERREUR', 'Erreur')], default='EN_ATTENTE', max_length=12)),
                ('synchronise_le', models.DateTimeField(blank=True, null=True)),
                ('erreur', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['cree_le'],
            },
        ),
        migrations.AddField(
            model_name='dossier',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mission',
            name='modifie_le',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ConflitSynchronisation',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modele', models.CharField(choices=[('Dossier', 'Dossier'), ('DossierCommentaire', 'Commentaire de dossier'), ('DossierHistorique', 'Historique de dossier'), ('DeclarationSecurite', 'Déclaration de sécurité'), ('Mission', 'Mission'), ('MessageMeshLog', 'Message mesh')], max_length=30)),
                ('objet_id', models.UUIDField()),
                ('payload_local', models.JSONField(help_text="Ce que le satellite tentait d'appliquer.")),
                ('etat_central_au_conflit', models.JSONField(help_text="Instantané de l'état central au moment du conflit, pour comparaison.")),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'arbitrage"), ('RESOLU_GARDE_CENTRAL', 'Résolu — version centrale conservée'), ('RESOLU_GARDE_LOCAL', 'Résolu — version locale appliquée')], default='EN_ATTENTE', max_length=25)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('resolu_le', models.DateTimeField(blank=True, null=True)),
                ('resolu_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflits_synchronisation_resolus', to=settings.AUTH_USER_MODEL)),
                ('satellite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflits_synchronisation', to='core.satellite')),
            ],
            options={
                'ordering': ['-cree_le'],
            },
        ),
    ]
