# Generated by Django 5.2.17 on 2026-09-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0160_evenementsynchronisation_dossier_modifie_le_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compagnonmeshcore',
            name='region_tag',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contactmeshcore',
            name='nombre_sauts',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmeshcore',
            name='region_tag',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
