# Generated by Django 5.2.17 on 2026-09-18 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0161_compagnonmeshcore_region_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionZoneCommune',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commune_code', models.CharField(max_length=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('crise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions_zone_communes', to='core.crisis')),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions_zone_crises', to='core.institution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('crise', 'commune_code'), name='uq_contribution_zone_crise_commune')],
            },
        ),
    ]
