# Generated by Django 5.2.17 on 2026-09-18 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0162_contributionzonecommune'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='convention_sous_traitance_acceptee_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='convention_sous_traitance_acceptee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_sous_traitance_acceptees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='institution',
            name='convention_sous_traitance_version',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
