# Generated by Django 5.2.17 on 2026-09-19 19:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0163_institution_convention_sous_traitance_acceptee_le_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeMobilisation',
            fields=[
                ('environment', models.CharField(choices=[('PROD', 'Production'), ('DEMO', 'Démonstration')], default='PROD', max_length=4)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_demande', models.CharField(choices=[('MISE_A_DISPOSITION', 'Se mettre à disposition'), ('SE_RENDRE_A', 'Se rendre à un endroit précis')], max_length=25)),
                ('lieu_texte', models.CharField(blank=True, max_length=255)),
                ('motif', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIVE', 'Active'), ('REVOQUEE', 'Révoquée')], default='ACTIVE', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_revocation', models.DateTimeField(blank=True, null=True)),
                ('jeton_verification', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('cible_institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_mobilisation_recues', to='core.institution')),
                ('cible_offre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_mobilisation_recues', to='core.offer')),
                ('cible_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_mobilisation_recues', to=settings.AUTH_USER_MODEL)),
                ('crise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mobilisation', to='core.crisis')),
                ('emetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_mobilisation_creees', to=settings.AUTH_USER_MODEL)),
                ('institution_emettrice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_mobilisation_emises', to='core.institution')),
                ('point_operationnel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_mobilisation', to='core.pointoperationnel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
